#! /bin/sh

. "${HOME}/.cache/wal/colors.sh"

#autostart apps
pgrep -x sxhkd > /dev/null || sxhkd &
xfce4-power-manager &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
xmodmap .Xmodmap &
nm-applet &
ibus-daemon -drxR &

#xrdb merge ~/.Xresources &
xrdb -merge -quiet ~/.cache/wal/colors.Xresources &
picom --experimental-backends &

# polybar
~/.config/polybar/launch.sh &

#wallpaper and nvim
#del .config/nvim && cp -r ~/Public/nvim_confs/base/nvim ~/.config/ &

#cd /home/pirate/Pictures/wall/ && ./testwal paradise.jpg &

# workspaces
bspc monitor -d 1 2 3 4 5 6

bspc config focus_follows_pointer true

bspc config top_padding 0

# borders
#bspc config focused_border_color "#282c34"
bspc config focused_border_color "$color1"
bspc config normal_border_color "$color0"
bspc config border_width 2
bspc config borderless_monocle true

#gaps
bspc config gapless_monocle false
bspc config window_gap 10
bspc config split_ratio 0.65

#moving floating windows and resize them with mouse, hold alt key
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

#rules
bspc rule -a Xfce4-terminal state=floating
bspc rule -a Xfce4-settings-manager state=floating
bspc rule -a openssh-askpass state=floating
bspc rule -a kdeconnect-app state=floating
bspc rule -a Pavucontrol state=floating
bspc rule -a vlc state=floating
bspc rule -a 'python3.10' state=floating
bspc rule -a LibreWolf desktop='^2' follow=on
bspc rule -a discord desktop='^6' follow=off
bspc rule -a spotify desktop='^5' follow=off
bspc rule -a Arcolinux-welcome-app.py follow=off
bspc rule -a code-oss desktop='^1'


feh --bg-fill forest.jpg &
